List<Map<String, String>> commonLanguagesWithFlags = [
  {"language": "English", "code": "US"},
  {"language": "Spanish", "code": "ES"},
  {"language": "Chinese (Simplified)", "code": "CN"},
  {"language": "Chinese (Traditional)", "code": "TW"},
  {"language": "Arabic", "code": "SA"},
  {"language": "Hindi", "code": "IN"},
  {"language": "Bengali", "code": "BD"},
  {"language": "Russian", "code": "RU"},
  {"language": "Portuguese", "code": "PT"},
  {"language": "Japanese", "code": "JP"},
  {"language": "German", "code": "DE"},
  {"language": "Korean", "code": "KR"},
  {"language": "French", "code": "FR"},
  {"language": "Turkish", "code": "TR"},
  {"language": "Italian", "code": "IT"},
  {"language": "Dutch", "code": "NL"},
  {"language": "Swedish", "code": "SE"},
  {"language": "Polish", "code": "PL"},
  {"language": "Indonesian", "code": "ID"},
  {"language": "Malay", "code": "MY"},
  {"language": "Thai", "code": "TH"},
  {"language": "Vietnamese", "code": "VN"},
  {"language": "Filipino", "code": "PH"},
  {"language": "Greek", "code": "GR"},
  {"language": "Hebrew", "code": "IL"},
  {"language": "Romanian", "code": "RO"},
];
