name: prime_ai_flutter_ui_kit
description: Prime AI Flutter UI Kit
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# Flutter version 3.16.5
# Dart version 3.2.3  
version: 1.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  pinput: ^3.0.1
  fl_country_code_picker: ^0.1.5
  share_plus: ^7.1.0
  super_tooltip: ^2.0.5
  flag: ^7.0.0
  audioplayers: ^5.2.1
  file_picker: ^5.5.0
  audio_waveforms: ^1.0.4
  assets_audio_player: ^3.1.1
  syncfusion_flutter_sliders: ^23.1.38
  top_modal_sheet: ^2.1.0
  flutter_switch: ^0.3.2
  flutter_colorpicker:
    path: colorpicker/flutter_colorpicker
  image_picker: ^0.8.4+2
  emoji_picker_flutter: ^1.6.1
  cupertino_will_pop_scope: ^1.2.1
  fluttertoast: ^8.2.2
  shared_preferences: ^2.2.3
  retrofit: ^4.1.0
  json_annotation: ^4.8.1
  dio: ^5.4.3+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: '>=7.0.0 <8.0.0'
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/flags/
    - assets/fonts/

  fonts:
    - family: Outfit_Light
      fonts:
        - asset: assets/fonts/Outfit-Light.ttf
    - family: Outfit_Regular
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf
    - family: Outfit_Medium
      fonts:
        - asset: assets/fonts/Outfit-Medium.ttf
    - family: Outfit_SemiBold
      fonts:
        - asset: assets/fonts/Outfit-SemiBold.ttf

