import 'package:prime_ai_flutter_ui_kit/config/string_config.dart';

final Map<String, String> ruRU = {
  StringConfig.languages: "Язык",
  StringConfig.profile: 'Настройки',
  StringConfig.logout: 'Удалить историю',
  StringConfig.history: 'История',
  StringConfig.more: 'Больше',
  StringConfig.chat: 'Чат',
  StringConfig.boardingTitle1:
      'Различные AI помощники, чтобы\nпомочь вам больше',
  StringConfig.boardingTitle2: 'Лучшее AI приложение для чата\nэтого века',
  StringConfig.boardingTitle3:
      'Попробуйте премиум для\nнеограниченного использования',
  StringConfig.boardingDescription1:
      'Мы рады приветствовать вас в AI, мощный\nчат-бот на основе AI, разработанный чтобы помочь вам',
  StringConfig.buttonSkip: 'Пропустить',
  StringConfig.buttonNext: 'Далее',
  StringConfig.buttonGetStarted: 'Начать',
  StringConfig.buttonSignIn: 'Войти',
  StringConfig.buttonSignUp: 'Зарегистрироваться',
  StringConfig.buttonContinue: 'Продолжить',
  StringConfig.buttonReset: 'Сброс',
  StringConfig.buttonVerify: 'Подтвердить',
  StringConfig.buttonStartChat: 'Начать чат',
  StringConfig.buttonSubmit: 'Отправить',
  StringConfig.buttonDelete: 'Удалить',
  StringConfig.buttonCancel: 'Отмена',
  StringConfig.buttonGenerateNow: 'Генерировать сейчас',
  StringConfig.buttonGenerateImage: 'Создать изображение',
  StringConfig.buttonGenerate: 'Создать',
  StringConfig.buttonDownloadNow: 'Скачать сейчас',
  StringConfig.buttonDiscard: 'Сбросить',
  StringConfig.buttonUpgradeToPro: 'Обновиться до PRO',
  StringConfig.buttonLogout: 'Выйти',
  StringConfig.buttonConfirmPayment: 'Подтвердить оплату',
  StringConfig.buttonConfirm: 'Подтвердить',
  StringConfig.signInWithAccount: 'Войти в ваш аккаунт',
  StringConfig.signInWithDescription:
      'Пожалуйста, введите данные ниже, чтобы продолжить',
  StringConfig.email: 'Электронная почта',
  StringConfig.password: 'Пароль',
  StringConfig.enterEmail: 'Введите электронную почту',
  StringConfig.enterPassword: 'Введите пароль',
  StringConfig.rememberMe: 'Запомнить меня',
  StringConfig.forgotPassword: 'Забыли пароль?',
  StringConfig.orContinueWith: 'Или продолжить с',
  StringConfig.doYouHaveNoAccount: 'У вас нет аккаунта? ',
  StringConfig.createNewAccount: 'Создать новый аккаунт',
  StringConfig.createNewAccountDescription:
      'Пожалуйста, введите ваш email и пароль\nчтобы создать аккаунт',
  StringConfig.alreadyHaveAnAccount: 'Уже есть аккаунт? ',
  StringConfig.enterOTPCodeHere: 'Введите код OTP здесь',
  StringConfig.enterOTPCodeDescription:
      'Мы отправили код на вашу электронную почту',
  StringConfig.resendCodeText: 'Вы можете повторно отправить код через',
  StringConfig.resendCodeTimer: ' 55 ',
  StringConfig.resendCodeTimerSecond: 'с',
  StringConfig.completeYourProfile: 'Заполните ваш профиль',
  StringConfig.completeYourProfileDescription:
      'Пожалуйста, заполните ваш профиль. Не беспокойтесь, только вы можете видеть ваши личные данные. Никто другой не сможет их увидеть. Или вы можете пропустить этот шаг.',
  StringConfig.fullName: 'Полное имя',
  StringConfig.name: 'Имя',
  StringConfig.phoneNumber: 'Номер телефона',
  StringConfig.gender: 'Пол',
  StringConfig.dateOfBirth: 'Дата рождения',
  StringConfig.female: 'Женский',
  StringConfig.other: 'Другой',
  StringConfig.flagInitial: 'assets/flags/in.png',
  StringConfig.resetYourPassword: 'Сброс пароля',
  StringConfig.resetYourPasswordDescription:
      'Пожалуйста, введите вашу электронную почту, и мы отправим вам код OTP на следующем шаге для сброса пароля.',
  StringConfig.createNewPassword: 'Создать новый пароль',
  StringConfig.createNewPasswordDescription: 'Пожалуйста, введите ваш пароль',
  StringConfig.confirmPassword: 'Подтвердите пароль',
  StringConfig.aiAssistant: 'AI помощник',
  StringConfig.welcomeTo: 'Добро пожаловать в',
  StringConfig.aiAssistantDescription:
      'Начните чат с AI помощником сейчас. Вы\nможете спросить меня что угодно.',
  StringConfig.askMeAnything: 'Спросите меня что угодно..',
  StringConfig.capabilities: 'Возможности',
  StringConfig.rememberConversation:
      'Запоминает, что пользователь сказал ранее\nв разговоре',
  StringConfig.allowCorrections:
      'Позволяет пользователю вносить поправки\nпосле',
  StringConfig.trainedRequests: 'Обучен отклонять неподобающие\nзапросы',
  StringConfig.limitations: 'Ограничения',
  StringConfig.occasionallyInform:
      'Может иногда генерировать неверную\nинформацию',
  StringConfig.occasionallyInstruction:
      'Может иногда давать вредные\nуказания или предвзятый контент',
  StringConfig.limitedKnowledge:
      'Ограниченное знание о мире и\nсобытиях после 2022 года',
  StringConfig.helloThere: 'Привет, там',
  StringConfig.howCanIHelpYou: 'Чем я могу вам помочь сегодня?',
  StringConfig.iAIPreviewMessage:
      'Я предварительная версия AI, поэтому я всё ещё учусь. Иногда я могу сказать что-то странное. Не сердитесь на меня, я просто пытаюсь стать лучше!',
  StringConfig.showMeWhatYouDo: 'Покажи, что ты можешь',
  StringConfig.iAIPreviewMessage2String:
      'Я предварительная версия AI, поэтому всё ещё учусь. Иногда я могу сказать что-то странное. Не сердитесь на меня, я просто пытаюсь стать лучше!\n      ·  Lorem Ipsum - это просто фиктивный\n         текст полиграфии и\n         наборного дела\n      ·  Lorem Ipsum - это просто фиктивный\n         текст',
  StringConfig.regenerateResponse: 'Перегенерировать ответ',
  StringConfig.stopGenerating: 'Остановить генерацию...',
  StringConfig.provideAdditionalFeedback: 'Предоставить дополнительный отзыв',
  StringConfig.whatAboutLikeResponse: 'Что вам понравилось в ответе?',
  StringConfig.iDontLikeIt: 'Мне не нравится',
  StringConfig.iCantBear: 'Я не могу терпеть',
  StringConfig.iAmNotKeepOn: 'Мне это не по душе',
  StringConfig.deleteChat: 'Удалить чат',
  StringConfig.changeModel: 'Изменить модель',
  StringConfig.deleteChats: 'Удалить чаты',
  StringConfig.areYouSureDeleteChats:
      'Вы уверены, что хотите удалить все чаты?',
  StringConfig.selectModelToChange: 'Выберите модель для изменения',
  StringConfig.moreView: 'Больше',
  StringConfig.aiSpecialFeature: 'Особые возможности AI',
  StringConfig.allTab: 'Все',
  StringConfig.writingTab: 'Письмо',
  StringConfig.creativeTab: 'Креатив',
  StringConfig.businessTab: 'Бизнес',
  StringConfig.lawsTab: 'Законы',
  StringConfig.developersTab: 'Разработчики',
  StringConfig.socialTab: 'Социальные',
  StringConfig.othersTab: 'Другие',
  StringConfig.seeAll: 'Смотреть все',
  StringConfig.translateLanguage: 'Перевод\nязыка',
  StringConfig.translateLanguageInline: 'Перевод языка',
  StringConfig.articles: 'Статьи',
  StringConfig.essay: 'Эссе',
  StringConfig.story: 'История',
  StringConfig.summarize: 'Обобщить',
  StringConfig.translateFromAnother: 'Перевести с одного\nязыка на другой.',
  StringConfig.generateWellWritten:
      'Создайте хорошо написанные\nстатьи на любую тему,\nкоторую вы хотите.',
  StringConfig.generateEssayWellWritten:
      'Создайте хорошо написанное\nэссе на любую тему, которую\nвы хотите.',
  StringConfig.extractKeyPoints:
      'Извлечение ключевых моментов\nиз длинных текстов.',
  StringConfig.storyTopic: 'Напишите историю на любую\nтему.',
  StringConfig.articlesForGoogle: 'напишите 100 слов статью для Google',
  StringConfig.articlesForGoogleDescribeChat:
      'В мире технологий Google стал домашним именем, революционизируя доступ к информации и взаимодействие с миром. С момента своего основания в 1998 году Google быстро эволюционировал от скромного поискового двигателя до технологического гиганта, предлагающего множество услуг и продуктов.\n\nGoogle Search, флагманский продукт компании, остаётся основным источником для ответа на вопросы, от тривиальных до жизненно важных запросов. Алгоритмы поиска непрерывно улучшаются, улучшая пользовательский опыт. Google Maps революционизировал навигацию, а такие сервисы, как Google Docs и Drive, революционизировали сотрудничество и облачное хранилище.\n\nКроме продуктов, Google стал пионером в разработке автомобилей с самоуправлением и инвестировал в возобновляемую энергию.',
  StringConfig.translateSentence:
      'Переведите следующие предложения на японский «Как создать новую моду»',
  StringConfig.translatedLanguage: '新しいファッションの作り方」',
  StringConfig.translateSentence2:
      'Переведите следующие предложения на голландский «Как создать последние дизайнерские инструменты»',
  StringConfig.translatedLanguage2:
      'Hoe u de nieuwste ontwerp- en ontwerptools maakt',
  StringConfig.answerInterview: 'Ответить на\nвопросы интервью',
  StringConfig.explainCode: 'Объяснить код',
  StringConfig.generateAAnswer: 'Создать ответ на\nвопросы интервью.',
  StringConfig.generateStories: 'Создавать рассказы по\nлюбой заданной теме.',
  StringConfig.writeCode: 'Написать код',
  StringConfig.writeApp:
      'Написать приложение, сайты\nна любом языке\nпрограммирования.',
  StringConfig.birthday: 'День рождения',
  StringConfig.tellAJoke: 'Расскажите шутку',
  StringConfig.createSincere:
      'Создайте искренние\nпожелания на день\nрождения для близких.',
  StringConfig.writeJokes: 'Напишите забавные шутки\nи заставьте их смеяться.',
  StringConfig.songLyrics: 'Тексты песен',
  StringConfig.storyTeller: 'Рассказчик',
  StringConfig.imageGenerator: 'Генератор изображений',
  StringConfig.describeImageWhatToGenerate:
      'Опишите изображение, которое хотите создать...',
  StringConfig.imageSize: 'Размер изображения',
  StringConfig.imageStyle: 'Стиль изображения',
  StringConfig.selectSize: 'Выберите размер',
  StringConfig.selectStyle: 'Выберите стиль',
  StringConfig.generateImagesDescription:
      'Создавайте изображения по детальному\nтекстовому описанию.',
  StringConfig.size80: '80x80',
  StringConfig.size256: '256x256',
  StringConfig.size512: '512x512',
  StringConfig.size1024: '1024x1024',
  StringConfig.size1440: '1440x1440',
  StringConfig.allDropdownText: 'Все',
  StringConfig.popularDropdownText: 'Популярные',
  StringConfig.movementDropdownText: 'Движения',
  StringConfig.themesDropdownText: 'Темы',
  StringConfig.techniquesDropdownText: 'Методы',
  StringConfig.effectDropdownText: 'Эффект',
  StringConfig.videoGenerator: 'Генератор видео',
  StringConfig.startBlank: 'Начать с пустого',
  StringConfig.getStartedWithEmptyCanvas: 'Начать с пустого холста.',
  StringConfig.startWithTemplates: 'Начать с шаблонов',
  StringConfig.officeInterior: 'Офисный интерьер',
  StringConfig.business: 'Бизнес',
  StringConfig.digitalMarketing: 'Цифровой маркетинг',
  StringConfig.finance: 'Финансы',
  StringConfig.healthcare: 'Здравоохранение',
  StringConfig.sportAndFitness: 'Спорт и фитнес',
  StringConfig.industry: 'Индустрия',
  StringConfig.socialMedia: 'Социальные сети',
  StringConfig.scene: 'Сцена',
  StringConfig.framing: 'Обрамление',
  StringConfig.avatar: 'Аватар',
  StringConfig.background: 'Фон',
  StringConfig.text: 'Текст',
  StringConfig.music: 'Музыка',
  StringConfig.language: 'Язык',
  StringConfig.style: 'Стиль',
  StringConfig.voice: 'Голос',
  StringConfig.uploadAVideoAudio: 'Загрузить голосовой файл',
  StringConfig.zeroPointFiveSecond: '0.5с',
  StringConfig.second3: '3с',
  StringConfig.second5: '5с',
  StringConfig.second10: '10с',
  StringConfig.second15: '15с',
  StringConfig.second20: '20с',
  StringConfig.onePointZeroX: '1.0х',
  StringConfig.speed1point5: '1.5х',
  StringConfig.speed2: '2.0х',
  StringConfig.speed2point5: '2.5х',
  StringConfig.speed5point: '0.5х',
  StringConfig.scriptPasteHere: 'Напишите или вставьте ваш сценарий здесь...',
  StringConfig.script: 'Сценарий',
  StringConfig.character: '/3280 символов',
  StringConfig.selectAvtar: 'Выберите Аватар',
  StringConfig.addAvtar: 'Добавить Аватар',
  StringConfig.selectFraming: 'Выберите обрамление',
  StringConfig.framing1: '1:1',
  StringConfig.framing2: '16:9',
  StringConfig.framing3: '9:16',
  StringConfig.framing4: '9:16',
  StringConfig.framing5: '7:5',
  StringConfig.framing6: '5:7',
  StringConfig.framing7: '2:3',
  StringConfig.selectBackground: 'Выберите фон',
  StringConfig.color: 'Цвет',
  StringConfig.images: 'Изображения',
  StringConfig.uploadImage: 'Загрузить изображение',
  StringConfig.scene1: 'Сцена 1',
  StringConfig.sceneNumber: 'Сцена ',
  StringConfig.selectLanguage: 'Выберите язык',
  StringConfig.selectVoice: 'Выберите голос',
  StringConfig.voiceFRochel: 'Рэйчел',
  StringConfig.voiceFEmily: 'Эмили',
  StringConfig.voiceFDorothy: 'Дороти',
  StringConfig.voiceFBella: 'Белла',
  StringConfig.voiceFCharlotte: 'Шарлотта',
  StringConfig.voiceMRajesh: 'Раджеш',
  StringConfig.voiceMKevin: 'Кевин',
  StringConfig.voiceFemale: 'Женский',
  StringConfig.voiceMale: 'Мужской',
  StringConfig.generatingVideo: 'Создание видео... ',
  StringConfig.generatingVideoDescription:
      'Создание видео может занять несколько секунд.\nПожалуйста, не выходите из приложения.',
  StringConfig.pixel720: '720p',
  StringConfig.yourVideoIsComplete: 'Ваше видео готово',
  StringConfig.videoViewDescription:
      'Созданное видео готово, скачайте его сейчас. Ознакомьтесь с нашими профессиональными функциями, чтобы получить все преимущества\nбез каких-либо ограничений.',
  StringConfig.discardVideo: 'Удалить видео',
  StringConfig.discardVideoDescription:
      'Вы уверены, что хотите удалить это видео?',
  StringConfig.videoFileSize: 'Примерный размер файла: 43.7М',
  StringConfig.resolution: 'Разрешение',
  StringConfig.resolution480p: '480p',
  StringConfig.resolution640p: '640p',
  StringConfig.resolution720p: '720p',
  StringConfig.resolution1080p: '1080p',
  StringConfig.resolution1440p: '1440p',
  StringConfig.quality: 'Качество',
  StringConfig.low: 'Низкое',
  StringConfig.medium: 'Среднее',
  StringConfig.high: 'Высокое',
  StringConfig.drawerHeader: 'Заголовок меню',
  StringConfig.item1: 'Элемент 1',
  StringConfig.item2: 'Элемент 2',
  StringConfig.chatsTab: 'Чаты',
  StringConfig.videosTab: 'Видео',
  StringConfig.noHistoryFound:
      'Извините, история не найдена. Пожалуйста, используйте\nэто приложение и создайте историю.',
  StringConfig.featureOfArtificialIntelligence:
      'Будущее\nИскусственного интеллекта',
  StringConfig.exploringVirtualReality: 'Исследование\nвиртуальной реальности',
  StringConfig.innovationInAge: 'Инновации в эпоху\nцифровой трансформации...',
  StringConfig.historyTime1: '00:03:30',
  StringConfig.historyTime2: '00:01:80',
  StringConfig.historyTime3: '00:02:10',
  StringConfig.historyToday: ' •   Сегодня',
  StringConfig.historyYesterday: ' •   Вчера',
  StringConfig.historyDay: ' •   12 Авг 2022',
  StringConfig.deleteHistory: 'Удалить историю',
  StringConfig.deleteVideo: 'Удалить видео',
  StringConfig.areYouSureDeleteThisVideo:
      'Вы уверены, что хотите удалить это видео?',
  StringConfig.areYouSureDeleteThisChat:
      'Вы уверены, что хотите удалить этот чат?',
  StringConfig.areYouSureDeleteHistory:
      'Вы уверены, что хотите удалить всю историю?',
  StringConfig.previous8Days: 'Последние 8 дней',
  StringConfig.previous25Days: 'Последние 25 дней',
  StringConfig.previousJulyDays: 'Июль',
  StringConfig.bDayWishesForEmployee:
      'Поздравления с днем рождения для сотрудника.',
  StringConfig.bDayWishesAndReflection:
      'Поздравления с днем рождения и размышления.',
  StringConfig.randomCharacterDetected: 'Обнаружены случайные символы.',
  StringConfig.reflectingOnIndependence: 'Размышления о независимости.',
  StringConfig.aiColorScheme: 'Цветовая схема AI.',
  StringConfig.chatHistoryTime1: '09:48PM',
  StringConfig.chatHistoryTime2: '11:58PM',
  StringConfig.chatHistoryTime3: '02:28AM',
  StringConfig.chatHistoryTime4: '03:09PM',
  StringConfig.chatHistoryTime5: '11:58PM',
  StringConfig.chatHistoryTime6: '01:11PM',
  StringConfig.videoTiming1: '02:13',
  StringConfig.videoTiming2: '03:30',
  StringConfig.futureOfArtist: 'Будущее художника...',
  StringConfig.historyChat: 'История чата',
  StringConfig.personalInfo: 'Личная информация',
  StringConfig.languages: 'Языки',
  StringConfig.darkMode: 'Темный режим',
  StringConfig.faqs: 'Часто задаваемые вопросы',
  StringConfig.logout: 'Удалить историю',
  StringConfig.logoutDescription:
      'Вы уверены, что хотите выйти из этой учетной записи?',
  StringConfig.rahulRana: 'Рахул Рана',
  StringConfig.exampleEmail: 'example@gmail.com',
  StringConfig.mobileNumber: '00000 00000',
  StringConfig.male: 'Мужской',
  StringConfig.dob: '22.04.2002',
  StringConfig.arabic: 'Арабский',
  StringConfig.chinese: 'Китайский',
  StringConfig.german: 'Немецкий',
  StringConfig.english: 'Английский',
  StringConfig.france: 'Французский',
  StringConfig.hindi: 'Хинди',
  StringConfig.italian: 'Итальянский',
  StringConfig.russian: 'Русский',
  StringConfig.spanish: 'Испанский',
  StringConfig.whatIsPremium: 'Что такое Премиум?',
  StringConfig.howToUsePremium: 'Как использовать Премиум?',
  StringConfig.whatIsAI: 'Что такое AI?',
  StringConfig.canIUsePrime:
      'Могу ли я использовать Prime в коммерческих целях?',
  StringConfig.whatDoIUsePrimeApp: 'Для чего я использую приложение Prime?',
  StringConfig.faqDescription1:
      'Премиум - это цена, уплаченная за что-то выше и сверх его основной стоимости. Его можно использовать для обозначения цены на страхование, продукт или услугу.',
  StringConfig.upgradeToPro: 'Обновление до PRO',
  StringConfig.enjoyAllFeatures:
      'Наслаждайтесь всеми функциями и преимуществами без\nограничений',
  StringConfig.feature1: 'Удалить рекламу и водяные знаки',
  StringConfig.feature2: 'Неограниченная генерация видео',
  StringConfig.feature3: '50 ГБ облачного хранения и синхронизации',
  StringConfig.feature4: 'Скачивание видео в высоком разрешении',
  StringConfig.feature5: 'Более быстрое время обработки',
  StringConfig.feature6: 'Эксклюзивные функции и обновления',
  StringConfig.feature7: 'Интеграция с инструментами сторонних производителей',
  StringConfig.feature8: 'Доступ к премиум шаблонам',
  StringConfig.feature9: 'Продвинутые инструменты AI для редактирования',
  StringConfig.feature10: 'Функции для командной работы и сотрудничества',
  StringConfig.feature11: 'Приоритетная поддержка клиентов',
  StringConfig.feature12: 'Приоритетный доступ к новым функциям',
  StringConfig.feature13: 'Скачивание видео в высоком разрешении',
  StringConfig.feature14: 'Более быстрое время обработки',
  StringConfig.choosePlan: 'Выберите план',
  StringConfig.dollar20: '\$20',
  StringConfig.dollar40: '\$40',
  StringConfig.dollar70: '\$70',
  StringConfig.month1: '/ 1 месяц',
  StringConfig.month6: '/ 6 месяцев',
  StringConfig.month12: '/ 12 месяцев',
  StringConfig.save10:
      'Станьте PRO и наслаждайтесь всеми преимуществами (экономьте 10%)',
  StringConfig.save40:
      'Станьте PRO и наслаждайтесь всеми преимуществами (экономьте 40%)',
  StringConfig.removeAddsAndWatermark: 'Удалить рекламу и водяные знаки',
  StringConfig.unlimitedVideoGeneration: 'Неограниченная генерация видео',
  StringConfig.cloudStorageOf50GB: '50 ГБ облачного хранения и синхронизации',
  StringConfig.collaborationAndTeamFeature:
      'Функции для командной работы и сотрудничества',
  StringConfig.priorityCustomerSupport: 'Приоритетная поддержка клиентов',
  StringConfig.downloadVideoInHighResolution:
      'Скачивание видео в высоком разрешении',
  StringConfig.fasterProcessingTimes: 'Более быстрое время обработки',
  StringConfig.priorityAccessToNewFeatures:
      'Приоритетный доступ к новым функциям',
  StringConfig.selectPayment: 'Выберите способ оплаты',
  StringConfig.payPal: 'PayPal',
  StringConfig.googlePay: 'Google Pay',
  StringConfig.applePay: 'Apple Pay',
  StringConfig.visaCard: '**** **** **** 5567',
  StringConfig.americanExpressCard: '**** **** **** 5342',
  StringConfig.reviewSummary: 'Итоги обзора',
  StringConfig.amount: 'Сумма',
  StringConfig.tax: 'Налог',
  StringConfig.total: 'Итого',
  StringConfig.dollar20By1: '1 x \$20',
  StringConfig.search: 'Поиск',
  StringConfig.noRecentEmoji: 'Нет недавних эмодзи',
  StringConfig.typeAMessage: 'Введите здесь',
  StringConfig.yourImageDownloadSuccess: 'Изображение успешно загружено',
  StringConfig.textCopied: 'Текст скопирован!',
  StringConfig.thisCodeIsIncorrect: 'Этот код неверен',
  StringConfig.codeRequired: 'Необходим код',
  StringConfig.emailRequired: 'Необходим email',
  StringConfig.passwordRequired: 'Необходим пароль',
};
